version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
  prisma-postgres-api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    stdin_open: true
    container_name: graphql-api
    depends_on:
      - postgres
    ports:
      - "3001:3001"
    restart: always

volumes:
  postgres-data: